### ISSUE TITLE
python crash on first server request

### ISSUE THREAD

**Issue by T0jan** [ezbz/gitlabber#101]
# Description

After a few month I tried gitlabber again only to see it is not working anymore. it already worked a few month ago perfectly but now it seems to fail on the very first request.

# Output

gitlabber -t ****** -url **local-gitlabber-instance** -p --verbose
Traceback (most recent call last):
  File "/home/usr_name/.local/bin/gitlabber", line 8, in <module>
    sys.exit(main())
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlabber/cli.py", line 43, in main
    tree.load_tree()
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlabber/gitlab_tree.py", line 144, in load_tree
    self.load_gitlab_tree()
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlabber/gitlab_tree.py", line 120, in load_gitlab_tree
    groups = self.gitlab.groups.list(as_list=False, archived=self.archived)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/exceptions.py", line 311, in wrapped_f
    return f(*args, **kwargs)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/mixins.py", line 241, in list
    obj = self.gitlab.http_list(path, **data)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/client.py", line 824, in http_list
    return GitlabList(self, url, query_data, **kwargs)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/client.py", line 980, in __init__
    self._query(url, query_data, **self._kwargs)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/client.py", line 990, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "/home/usr_name/.local/lib/python3.9/site-packages/gitlab/client.py", line 680, in http_request
    result = self.session.request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'rl/api/v4rl/api/v4/groups': No schema supplied. Perhaps you meant http://rl/api/v4rl/api/v4/groups?

# Versions

 - OS: Ubuntu 21.10
 - Python Version: 3.9.7
 - GitLab Community Edition [14.10.0](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v14.10.0)
 - Gitlabber version 1.1.9
 - 
# Additional Context

I also tried gitlabber on a Ubuntu 20.04. PC with python version 3.8.x with the same result. Accessing the server via curl and the access token is working on both machines.

**Comment by ezbz** [comment]
Malformed URL provided
