### ISSUE TITLE
console errors while trying to print gitlab tree

### ISSUE THREAD

**Issue by biswa1shaw** [ezbz/gitlabber#120]
console errors while trying to print gitlab tree

` gitlabber -t <token_id> -u <on-prem-host-address> --verbose -i <location> . -p`

same command used to work before .... maybe something has changed in the gitlab server 

On-prem GitLab Enterprise Edition [14.10.5-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v14.10.5-ee)
gitlabber version - 1.1.9

Can you please say what might be causing this error 
```
/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py:120: DeprecationWarning: `as_list=False` is deprecated and will be removed in a future version. Use `iterator=True` instead. (python-gitlab: /home/bsh/.local/lib/python3.10/site-packages/gitlab/client.py:915)
  groups = self.gitlab.groups.list(as_list=False, archived=self.archived)
* loading tree: 0.6%|▍                                                                               | 1/161, group=Backup/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py:109: DeprecationWarning: `as_list=False` is deprecated and will be removed in a future version. Use `iterator=True` instead. (python-gitlab: /home/bsh/.local/lib/python3.10/site-packages/gitlab/client.py:915)
  subgroups = group.subgroups.list(as_list=False, archived=self.archived)
* loading tree: 0.6%|▍                                                                               | 1/161, group=Backup/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py:104: DeprecationWarning: `as_list=False` is deprecated and will be removed in a future version. Use `iterator=True` instead. (python-gitlab: /home/bsh/.local/lib/python3.10/site-packages/gitlab/client.py:915)
  projects = group.projects.list(as_list=False, archived=self.archived)
* loading tree: 3.6%|██▉                                                                             | 6/166, group=data-productsTraceback (most recent call last):
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/exceptions.py", line 325, in wrapped_f
    return f(*args, **kwargs)
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/client.py", line 832, in http_get
    result = self.http_request(
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/client.py", line 798, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Group Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/gitlabber", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/cli.py", line 43, in main
    tree.load_tree()
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py", line 144, in load_tree
    self.load_gitlab_tree()
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py", line 127, in load_gitlab_tree
    self.get_subgroups(group, node)
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py", line 116, in get_subgroups
    self.get_subgroups(subgroup, node)
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py", line 116, in get_subgroups
    self.get_subgroups(subgroup, node)
  File "/usr/local/lib/python3.10/dist-packages/gitlabber/gitlab_tree.py", line 112, in get_subgroups
    subgroup = self.gitlab.groups.get(subgroup_def.id)
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/v4/objects/groups.py", line 330, in get
    return cast(Group, super().get(id=id, lazy=lazy, **kwargs))
  File "/home/bsh/.local/lib/python3.10/site-packages/gitlab/exceptions.py", line 327, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Group Not Found
```

the 404 group not found might indicate that the group does not exist .... but the location is correct and trying to print the structure from the root also has the same error. The verbose flag does not print anything else either

**Comment by ezbz** [comment]
There are a number of cases where Gitlab returns a [404](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/29296#note_80474729) for a group that you can see in the UI but cannot access through the API
If you are the on-prem host admin maybe you can look into that or contact the admin and provide more information on the issue (does cUrl to the same server work?)

**Comment by ezbz** [comment]
no response, closing.
