### ISSUE TITLE
exceptions.GitlabHttpError: 503 

### ISSUE THREAD

**Issue by hongsongp97** [ezbz/gitlabber#23]
```gitlabber -u https://gitlab.com/xxx -t **** --verbose -p .```
```
2020-07-19 07:41:54,611 - gitlabber.cli - INFO - Reading projects tree from gitlab at [https://gitlab.com/myakachain]
2020-07-19 07:41:54,611 - gitlabber.cli - INFO - Reading projects tree from gitlab at [https://gitlab.com/myakachain]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/mixins.py", line 141, in list
    obj = self.gitlab.http_list(path, **data)
  File "/usr/local/lib/python3.7/site-packages/gitlab/__init__.py", line 656, in http_list
    return GitlabList(self, url, query_data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/__init__.py", line 784, in __init__
    self._query(url, query_data, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/__init__.py", line 789, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/__init__.py", line 575, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 503: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>Checking your Browser - GitLab</title>
  <style>body{color:#666;text-align:center;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;margin:auto;font-size:14px;display:flex;flex-direction:column;align-items:center;justify-content:center}hr{max-width:800px;margin:18px auto;border:0;border-top:1px solid #eee;border-bottom:1px solid #fff}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>
<script type="text/javascript">
  //<![CDATA[
  (function(){

    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
...
```

**Comment by hongsongp97** [comment]
I re-tried with cmd ```gitlabber -u https://username@gitlab.com/xxx -t **** --verbose -p .```
So, it works!

**Comment by almeidaxan** [comment]
@hongsongp97 Besides including your username at the URL, did you do anything else?

I'm facing the same problem as you on #31, but adding my username to the URL didn't work.
