### ISSUE TITLE
gitlabber stops at 90,7%

### ISSUE THREAD

**Issue by jjwhatever** [ezbz/gitlabber#36]
Try to get access to our Internal git via gitlabber but it stops with these error at 90,7%
Maybe you can help:

[15:01:50][User@MDXN00057110:~/tmp2]$ gitlabber -t <TOKEN> -u https://git.tech.rz.db.de -p
* loading tree: 90.7%|██████████████████████████████████████████████████████████████████████████████████████████▋         | 206/227, project=cloudia-iamTraceback (most recent call last):      
  File "/usr/lib/python3.6/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/gitlab/mixins.py", line 50, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/lib/python3.6/site-packages/gitlab/__init__.py", line 593, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/usr/lib/python3.6/site-packages/gitlab/__init__.py", line 568, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 500: 500 Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/gitlabber", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/gitlabber/cli.py", line 36, in main
    tree.load_tree()
  File "/usr/lib/python3.6/site-packages/gitlabber/gitlab_tree.py", line 130, in load_tree
    self.load_gitlab_tree()
  File "/usr/lib/python3.6/site-packages/gitlabber/gitlab_tree.py", line 113, in load_gitlab_tree
    self.get_subgroups(group, node)
  File "/usr/lib/python3.6/site-packages/gitlabber/gitlab_tree.py", line 100, in get_subgroups
    subgroup = self.gitlab.groups.get(subgroup_def.id)
  File "/usr/lib/python3.6/site-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 500: 500 Internal Server Error

I Used:
gitlabber --version 1.1.1
GitLab Community Edition 13.3.9
Linux MDXN00057110 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
git version 2.16.4
Python 3.6.12

**Comment by ezbz** [comment]
Gitlabber experienced a 500 HTTP error from your gitlab server while trying to load  the tree. Please follow the instructions in the readme to get a detailed HTTP debug log from GitPython and check the source of the error.

**Comment by ezbz** [comment]
Closing due to inactivity
