### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by jrschumacher** [ezbz/gitlabber#8]
Getting the following error

`AttributeError: 'NoneType' object has no attribute 'rstrip'`

Python 3.7.6

**Comment by ezbz** [comment]
tests on [3.7.6](https://travis-ci.org/github/ezbz/gitlabber/jobs/685835469) pass, no rstrip in the code anywhere. What did you try to do?

**Comment by needleshaped** [comment]
Hello @ezbz , I believe @jrschumacher tried example provided, `only print the gitlab tree: gitlabber -p .`
I can repeat the error:
```
mkdir: created directory '/tmp/gitlab'
$ pwd
/tmp/gitlab
$ gitlabber --version
1.1.0
$ python --version
Python 3.8.2
$ gitlabber -p .
Traceback (most recent call last):
  File "/home/user/.local/bin/gitlabber", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/gitlabber/cli.py", line 25, in main
    tree = GitlabTree(args.url, args.token, args.method, includes,
  File "/home/user/.local/lib/python3.8/site-packages/gitlabber/gitlab_tree.py", line 23, in __init__
    self.gitlab = Gitlab(url, private_token=token)
  File "/home/user/.local/lib/python3.8/site-packages/gitlab/__init__.py", line 93, in __init__
    self._base_url = url.rstrip("/")
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by jrschumacher** [comment]
@ezbz @needleshaped sorry I was working on a patch. The issue is that there is no check whether or not the URL is defined. I can't test this due to not knowing enough Python to get an environment setup, but here is a diff of what appears to be needed:

```diff
diff --git a/gitlabber/cli.py b/gitlabber/cli.py
index 845b37f..645b6be 100644
--- a/gitlabber/cli.py
+++ b/gitlabber/cli.py
@@ -1,6 +1,7 @@
 
 import os
 import sys
+from urllib.parse import urlparse
 import logging
 import logging.handlers
 import enum
@@ -18,6 +19,17 @@ def main():
         print(VERSION)
         sys.exit(0) 
 
+    if args.token is None:
+        print('Requires a valid token')
+        sys.exit(1)
+
+    try:
+        urlparse(args.url)
+    except ValueError:
+        print('Requires a valid url')
+        sys.exit(1)
+
+
     config_logging(args)
     includes=split(args.include)
     excludes=split(args.exclude)
@@ -84,13 +96,13 @@ def parse_args(argv=None):
         '-t',
         '--token',
         metavar=('token'),
-        default=os.environ.get('GITLAB_TOKEN'),
+        default=os.environ.get('GITLAB_TOKEN', None),
         help='gitlab personal access token https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html')
     parser.add_argument(
         '-u',
         '--url',
         metavar=('url'),
-        default=os.environ.get('GITLAB_URL'),
+        default=os.environ.get('GITLAB_URL', 'https://gitlab.com'),
         help='gitlab url (e.g.: \'http://gitlab.mycompany.com\')')
     parser.add_argument(
         '--verbose',
```

**Comment by ezbz** [comment]
Sure will provide better validation for this, the example shows one usage with the `-u` and `-t` and then another example that assumes these are provided via environment variables. Aside from validation I'll clarify the documentation. Thanks for the feedback.

**Comment by ezbz** [comment]
Closed by https://github.com/ezbz/gitlabber/commit/8be5131a852be06ecaed06542325879a47515d9f

**Comment by Jack-Zcy** [comment]
so what is the problem？
