### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte ....

### ISSUE THREAD

**Issue by snikeguo** [ezbz/gitlabber#81]
```
* syncing projects: 0.6%|▍                                                                               | 1/173, cloneException in thread Thread-7:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 1.2%|▉                                                                               | 2/173, cloneException in thread Thread-9:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 1.7%|█▍                                                                              | 3/173, cloneException in thread Thread-11:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 2.3%|█▊                                                                              | 4/173, cloneException in thread Thread-13:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 2.9%|██▎                                                                             | 5/173, cloneException in thread Thread-15:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 3.5%|██▊                                                                             | 6/173, cloneException in thread Thread-17:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 4.0%|███▏                                                                            | 7/173, cloneException in thread Thread-19:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 4.6%|███▋                                                                            | 8/173, cloneException in thread Thread-21:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 5.2%|████▏                                                                           | 9/173, cloneException in thread Thread-23:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 5.8%|████▌                                                                           | 10/173, clonException in thread Thread-25:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 6.4%|█████                                                                           | 11/173, clonException in thread Thread-27:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 29: illegal multibyte sequence
* syncing projects: 6.9%|█████▌                                                                          | 12/173, clonException in thread Thread-29:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 7.5%|██████                                                                          | 13/173, clonException in thread Thread-31:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 8.1%|██████▍                                                                         | 14/173, clonException in thread Thread-33:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 8.7%|██████▉                                                                         | 15/173, clonException in thread Thread-35:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 9.2%|███████▍                                                                        | 16/173, clonException in thread Thread-37:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 9.8%|███████▊                                                                        | 17/173, clonException in thread Thread-39:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 10.4%|████████▎                                                                       | 18/173, cloException in thread Thread-41:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 11.0%|████████▊                                                                       | 19/173, cloException in thread Thread-43:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 11.6%|█████████▏                                                                      | 20/173, cloException in thread Thread-45:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 12.1%|█████████▋                                                                      | 21/173, cloException in thread Thread-47:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 12.7%|██████████▏                                                                     | 22/173, cloException in thread Thread-49:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 13.3%|██████████▋                                                                     | 23/173, cloException in thread Thread-51:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
* syncing projects: 93.1%|██████████████████████████████████████████████████████████████████████████▍     | 161/173, clException in thread Thread-327:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 33: illegal multibyte sequence
* syncing projects: 95.4%|████████████████████████████████████████████████████████████████████████████▎   | 165/173, clException in thread Thread-335:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 33: illegal multibyte sequence
* syncing projects: 96.5%|█████████████████████████████████████████████████████████████████████████████▏  | 167/173, clException in thread Thread-339:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 39: illegal multibyte sequence
* syncing projects: 97.1%|█████████████████████████████████████████████████████████████████████████████▋  | 168/173, clException in thread Thread-341:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x91 in position 51: illegal multibyte sequence
* syncing projects: 97.7%|██████████████████████████████████████████████████████████████████████████████▏ | 169/173, clException in thread Thread-343:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 39: illegal multibyte sequence
* syncing projects: 98.3%|██████████████████████████████████████████████████████████████████████████████▌ | 170/173, clException in thread Thread-345:
Traceback (most recent call last):
  File "c:\python3.9.5\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\python3.9.5\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3.9.5\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence
```

chinese

**Comment by ezbz** [comment]
can you please provide the command you tried to run and what platform and python version are you using?
