### ISSUE TITLE
Doesn't pull code into repositories

### ISSUE THREAD

**Issue by Aruyna** [ezbz/gitlabber#82]
I try clone all projects in my groups. Gitlabber finishes successfully and creates a hierarchy of groups and projects (folders) but they are empty (no code, no projects structures).

Command:
gitlabber -t [token] -u http://git... -r C:\Projects -n path

**Comment by StudyExchange** [comment]
Me too。

**Comment by Planche95** [comment]
Same here, tool is useless at the moment

**Comment by ezbz** [comment]
can you please run the command in verbose mode and provide the output?

**Comment by DrJMKatz** [comment]
```
2021-07-12 11:52:42,936 - gitlabber.git - DEBUG - Error cloning project <project>
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\gitlabber\git.py", line 78, in clone_or_pull_project
    git.Repo.clone_from(action.node.url, action.path)
  File "c:\program files\python39\lib\site-packages\git\repo\base.py", line 1111, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "c:\program files\python39\lib\site-packages\git\repo\base.py", line 1049, in _clone
    finalize_process(proc, stderr=stderr)
  File "c:\program files\python39\lib\site-packages\git\util.py", line 370, in finalize_process
    proc.wait(**kwargs)
  File "c:\program files\python39\lib\site-packages\git\cmd.py", line 447, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v <project>
  stderr: 'Cloning into <project>...
ssh_exchange_identification: read: Connection reset by peer
```

I was able to solve the issue by removing the passphrase from my ssh key

**Comment by ezbz** [comment]
Checking this error `GitCommandError(remove_password_if_present(self.args) ` I got to this [issue](https://github.com/gitpython-developers/GitPython/issues/1221) I upgraded GitPython to it's latest version and released `1.1.9`

**Comment by jaronaz** [comment]
Still having this issue with 1.1.9, upgraded to latest GitPython (3.1.20). 
`  raise GitCommandError(remove_password_if_present(self.args), status, errstr)`

Have used method=http instead of default ssh and then it works (after providing credentials)

**Comment by jaronaz** [comment]
`2021-08-30 09:17:25,745 - git.cmd - DEBUG - AutoInterrupt wait stderr: b"Cloning into './test security/test-Angular-Dist'...\ngit@gitlab.com: Permission denied (publickey,keyboard-interactive).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
2021-08-30 09:17:25,745 - gitlabber.git - DEBUG - Error cloning project ./test security/test-Angular-Dist
Traceback (most recent call last):
  File "/Users/name/.pyenv/versions/3.7.4/lib/python3.7/site-packages/gitlabber/git.py", line 78, in clone_or_pull_project
    git.Repo.clone_from(action.node.url, action.path)
  File "/Users/name/.pyenv/versions/3.7.4/lib/python3.7/site-packages/git/repo/base.py", line 1121, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/Users/name/.pyenv/versions/3.7.4/lib/python3.7/site-packages/git/repo/base.py", line 1059, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/name/.pyenv/versions/3.7.4/lib/python3.7/site-packages/git/util.py", line 385, in finalize_process
    proc.wait(**kwargs)
  File "/Users/name/.pyenv/versions/3.7.4/lib/python3.7/site-packages/git/cmd.py", line 446, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@gitlab.com:test-security/test-angular-dist.git ./test security/test-Angular-Dist
  stderr: 'Cloning into './test security/test-Angular-Dist'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'`

**Comment by ezbz** [comment]
Judging from the error above this is a permissions issue and not a gitlabber issue, I found [some indication](https://forum.gitlab.com/t/git-gitlab-com-permission-denied-publickey-keyboard-interactive-since-today-only/50362/6) that the issue might be with the OpenSSH installation on windows but I cannot test this,. 

Another possible solution is to look into your ssh keys and try running the same command that gitlabber runs from the above output 

```
git clone -v git@gitlab.com:test-security/test-angular-dist.git ./test security/test-Angular-Dist
```

and see if it succeeds
